-- Auto generated from GuardTemplate.xml at 15-07-2016 10:56:59 by hrose
Character = {
	Motivation = 0.6,
	Sociability = 0.5,
	FavouriteColor = { 1, 0.5586207, 0, 1 },
	Background = {
		FirstName = "THOMAS",
		LastName = "TEMPLATE",
		Nickname = {
			"Tommy",
			"T-dog",
			"Bumpkin",
			"Essex-boy",
		},
		DerogetoryName = {
			"Noggin",
		},
		FavouriteSwear = {
			"gosh-darn",
			"cripes",
		},
		FavouriteFood = {
			"toast",
			"slice of Wensleydale cheese",
		},
		FavouriteSnack = {
			"Babybell",
			"yoghurt",
			"apple",
		},
		FavouriteDrink = {
			"coffee",
			"hot chocolate",
		},
		BestFriend = {
			"Tristan",
		},
		RecipientPetName = {
			"Sweetums",
			"Dimps",
			"Tata",
		},
		SenderPetName = {
			"Hubby",
			"Tx",
		},
		FavouriteExclamation = {
			"Golly",
			"Oh man",
			"Cripes",
			"Gosh",
			"Geez",
			"Geewhiz",
			"Grrr",
			"gahhh!",
			"Ahhh",
			"WTF",
		},
		RandomHashtag = {
			"#ROFL",
			"#Grrr",
			"LMAO",
			"LOL",
			"#Tots",
			"#BigGuns",
			"#Life",
			"#WTF",
		},
		Mood = {
			"happy",
			"excited",
			"sad",
			"frustrated",
			"upset",
			"down",
			"good",
		},
		PastEvent = {
			"ate",
			"had lunch",
			"took a dump",
			"got up",
			"went to the toilet",
			"spoke to my doctor",
			"spoke to my lover",
			"checked the scores",
			"procrastinated",
		},
		FutureEvent = {
			"eat",
			"have lunch",
			"take a nap",
			"take a dump",
			"go to the toilet",
			"speak to my wife",
			"speak to my doctor",
			"check on the football",
			"procrastinate",
		},
	},
}
